import { jsPDF } from "jspdf";
import autoTable, { type CellHookData } from "jspdf-autotable";
import type { CheckResult, CSPDirectiveRule, CSPFinding, CSPPolicy, HeaderFinding, Policy, PolicyHeader, SeverityLevel } from "./types";

// Accepted by both a live ScanResult and a saved ScanReport - scan_number,
// policy_id and policy_version only exist on saved reports, so they're optional.
export interface PdfReportData {
  policy_name: string;
  target: string | null;
  fetched_status_code: number | null;
  score: number;
  grade: string;
  findings: HeaderFinding[];
  csp_finding: CSPFinding | null;
  scanned_at: string;
  scan_number?: number;
  policy_id?: string | null;
  policy_version?: string;
  scanner_version?: string | null;
}

export interface PdfOptions {
  /** The saved policy the scan used, when it is still at the scanned version. */
  policy?: Policy | null;
  /** Shown under the policy section, e.g. when the saved policy has since changed. */
  policyNote?: string | null;
}

type RGB = [number, number, number];

const PAGE_W = 595.28;
const MARGIN_X = 40;
const CONTENT_W = PAGE_W - MARGIN_X * 2;
const CONTENT_TOP = 84; // below the running header
const PAGE_BOTTOM = 782; // above the footer

const ACCENT: RGB = [255, 122, 26];
const ACCENT_SOFT: RGB = [255, 240, 229];
const INK: RGB = [28, 28, 32];
const MUTED: RGB = [110, 110, 118];
const LINE: RGB = [224, 224, 228];
const CARD: RGB = [248, 248, 250];
const PASS: RGB = [30, 140, 60];
const FAIL: RGB = [200, 50, 50];
const WARN: RGB = [180, 130, 20];

const STATUS_COLOR: Record<string, RGB> = { PASS, FAIL, WARNING: WARN, INFO: [90, 90, 90] };

function gradeColor(grade: string): RGB {
  if (grade === "A" || grade === "B") return PASS;
  if (grade === "C" || grade === "D") return WARN;
  return FAIL;
}

/** "Sep 26, 2026, 4:53 AM" - month spelled out, so it reads the same everywhere. */
function formatWhen(value: string | Date): string {
  return new Date(value).toLocaleString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
}

function finalY(doc: jsPDF): number {
  return (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? CONTENT_TOP;
}

function ensureSpace(doc: jsPDF, y: number, needed = 60): number {
  if (y + needed > PAGE_BOTTOM) {
    doc.addPage();
    return CONTENT_TOP;
  }
  return y;
}

function statusColorHook(statusColumnIndex: number) {
  return (hook: CellHookData) => {
    if (hook.section === "body" && hook.column.index === statusColumnIndex) {
      const color = STATUS_COLOR[String(hook.cell.raw)];
      if (color) {
        hook.cell.styles.textColor = color;
        hook.cell.styles.fontStyle = "bold";
      }
    }
  };
}

const TABLE_STYLE = {
  margin: { left: MARGIN_X, right: MARGIN_X, top: CONTENT_TOP },
  styles: { fontSize: 8, cellPadding: 5, overflow: "linebreak" as const, textColor: INK, lineColor: LINE, lineWidth: 0.4 },
  headStyles: { fillColor: ACCENT, textColor: 255, fontStyle: "bold" as const, lineWidth: 0 },
  alternateRowStyles: { fillColor: CARD },
};

/** The Hedr shield mark, drawn as vector shapes (no image asset needed). */
function drawLogo(doc: jsPDF, x: number, y: number, size: number): void {
  const k = size / 24;
  doc.setFillColor(...ACCENT_SOFT);
  doc.setDrawColor(...ACCENT);
  doc.setLineWidth(1.3);
  doc.setLineJoin("round");
  doc.lines(
    [
      [-7.5, 2.8],
      [0, 5.4],
      [0, 5, 3.2, 8.8, 7.5, 10.8],
      [4.3, -2, 7.5, -5.8, 7.5, -10.8],
      [0, -5.4],
    ],
    x + 12 * k,
    y + 2.5 * k,
    [k, k],
    "FD",
    true
  );
  doc.setLineWidth(1.6);
  doc.setLineCap("round");
  doc.lines([[2.2, 2.2], [4.4, -4.6]], x + 8.7 * k, y + 12.1 * k, [k, k], "S", false);
}

/** Running header (every page) and footer with page numbers. */
function decoratePages(doc: jsPDF, data: PdfReportData): void {
  const pages = doc.getNumberOfPages();
  const generated = formatWhen(new Date());
  const policyName = data.policy_name.length > 40 ? `${data.policy_name.slice(0, 39)}...` : data.policy_name;
  const footerLeft = [
    "Hedr",
    data.scan_number ? `Scan #${data.scan_number}` : null,
    `${policyName}${data.policy_version ? ` ${data.policy_version}` : ""}`,
  ]
    .filter(Boolean)
    .join("  ·  ");
  const footerMeta = `Generated by Hedr on ${generated}${data.scanner_version ? `  ·  Scanner v${data.scanner_version}` : ""}`;
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);

    drawLogo(doc, MARGIN_X, 22, 28);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(17);
    doc.setTextColor(...INK);
    doc.text("Hedr", MARGIN_X + 36, 42);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(...MUTED);
    doc.text("HTTP Security Header Policy Analyzer", MARGIN_X + 36, 53);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...ACCENT);
    doc.text("SECURITY SCAN REPORT", PAGE_W - MARGIN_X, 40, { align: "right" });
    doc.setDrawColor(...ACCENT);
    doc.setLineWidth(1.5);
    doc.line(MARGIN_X, 66, PAGE_W - MARGIN_X, 66);

    doc.setDrawColor(...LINE);
    doc.setLineWidth(0.5);
    doc.line(MARGIN_X, 804, PAGE_W - MARGIN_X, 804);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text(footerLeft, MARGIN_X, 817);
    doc.text(`Page ${i} of ${pages}`, PAGE_W - MARGIN_X, 817, { align: "right" });
    doc.setFontSize(7);
    doc.text(footerMeta, MARGIN_X, 828);
  }
}

const SECTION_GAP = 34; // space (with a divider line) between one section and the next

/**
 * Starts a section right after the previous one - after a gap and a divider
 * line - so the report reads as one continuous document. It only moves to a new
 * page when too little room is left for the heading to sit with some content.
 */
function beginSection(
  doc: jsPDF,
  y: number,
  title: string,
  subtitle: string | undefined,
  opts: { minSpace?: number; newPage?: boolean } = {}
): number {
  if (y > CONTENT_TOP && (opts.newPage || y + (opts.minSpace ?? 160) > PAGE_BOTTOM)) {
    doc.addPage();
    y = CONTENT_TOP;
  } else if (y > CONTENT_TOP) {
    doc.setDrawColor(...LINE);
    doc.setLineWidth(0.6);
    doc.line(MARGIN_X, y + SECTION_GAP / 2 - 4, PAGE_W - MARGIN_X, y + SECTION_GAP / 2 - 4);
    y += SECTION_GAP;
  }
  y += 12; // title baseline

  doc.setFillColor(...ACCENT);
  doc.roundedRect(MARGIN_X, y - 11, 3.5, 15, 1.5, 1.5, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...INK);
  doc.text(title, MARGIN_X + 11, y);
  y += 6;
  if (subtitle) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(...MUTED);
    const lines = doc.splitTextToSize(subtitle, CONTENT_W - 11) as string[];
    for (const line of lines) {
      y += 11;
      doc.text(line, MARGIN_X + 11, y);
    }
    y += 4;
  }
  return y + 10;
}

function statTile(doc: jsPDF, x: number, y: number, w: number, label: string, value: string, color: RGB): void {
  doc.setFillColor(...CARD);
  doc.setDrawColor(...LINE);
  doc.setLineWidth(0.5);
  doc.roundedRect(x, y, w, 46, 6, 6, "FD");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(...color);
  doc.text(value, x + w / 2, y + 22, { align: "center" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(...MUTED);
  doc.text(label.toUpperCase(), x + w / 2, y + 36, { align: "center" });
}

function summaryCard(doc: jsPDF, y: number, data: PdfReportData): number {
  const cardH = 128;
  doc.setFillColor(...CARD);
  doc.setDrawColor(...LINE);
  doc.setLineWidth(0.6);
  doc.roundedRect(MARGIN_X, y, CONTENT_W, cardH, 8, 8, "FD");
  doc.setFillColor(...ACCENT);
  doc.roundedRect(MARGIN_X, y, 5, cardH, 2.5, 2.5, "F");

  // Grade badge
  const color = gradeColor(data.grade);
  const cx = MARGIN_X + 52;
  const cy = y + 50;
  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(...color);
  doc.setLineWidth(3.5);
  doc.circle(cx, cy, 30, "FD");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(30);
  doc.setTextColor(...color);
  doc.text(data.grade, cx, cy + 10.5, { align: "center" });
  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  doc.text(`${data.score} / 100`, cx, cy + 46, { align: "center" });

  // Target + meta
  const textX = MARGIN_X + 108;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...MUTED);
  doc.text("TARGET", textX, y + 24);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(...INK);
  const targetLines = (doc.splitTextToSize(data.target ?? "Pasted response", CONTENT_W - 130) as string[]).slice(0, 2);
  doc.text(targetLines, textX, y + 39);
  const metaY = y + 39 + targetLines.length * 14 + 6;

  const meta: [string, string][] = [
    ["Scanned", formatWhen(data.scanned_at)],
    ["Policy", `${data.policy_name}${data.policy_version ? ` (${data.policy_version})` : ""}`],
  ];
  if (data.scan_number) meta.unshift(["Scan", `#${data.scan_number}`]);
  if (data.fetched_status_code != null) meta.push(["HTTP status", String(data.fetched_status_code)]);
  if (data.scanner_version) meta.push(["Scanner", `Hedr v${data.scanner_version}`]);
  let my = metaY;
  doc.setFontSize(8.5);
  for (const [label, value] of meta) {
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...MUTED);
    doc.text(label, textX, my);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...INK);
    doc.text((doc.splitTextToSize(value, CONTENT_W - 210) as string[])[0], textX + 62, my);
    my += 12;
  }
  return y + cardH + 14;
}

// ---- policy section ---------------------------------------------------------

interface PolicyView {
  name: string;
  description: string | null;
  version: string | null;
  headers: { header: string; required: boolean; expected: string }[];
  csp: CSPPolicy | null; // full structured CSP policy, when available
  cspChecks: { id: string; description: string; expected: string }[]; // reconstructed fallback
  cspEvaluated: boolean;
  fromSavedPolicy: boolean;
}

function buildPolicyView(data: PdfReportData, policy: Policy | null | undefined): PolicyView {
  if (policy) {
    return {
      name: policy.name,
      description: policy.description || null,
      version: `v${policy.version}`,
      headers: policy.headers.map((h: PolicyHeader) => ({
        header: h.header_name,
        required: h.required,
        expected: h.expected_value,
      })),
      csp: policy.csp_policy,
      cspChecks: [],
      cspEvaluated: Boolean(policy.csp_policy),
      fromSavedPolicy: true,
    };
  }
  // Rebuilt from what the scan actually evaluated, so it is exact for that scan.
  return {
    name: data.policy_name,
    description: null,
    version: data.policy_version ?? null,
    headers: data.findings.map((f) => ({ header: f.header, required: f.required, expected: f.policy_expected ?? "" })),
    csp: null,
    cspChecks: (data.csp_finding?.policy_checks ?? []).map((c) => ({
      id: c.id ?? "-",
      description: c.description,
      expected: c.expected ?? "-",
    })),
    cspEvaluated: Boolean(data.csp_finding),
    fromSavedPolicy: false,
  };
}

function ruleRestrictions(rule: CSPDirectiveRule): string {
  return [
    rule.disallow_wildcards && "no wildcards",
    rule.disallow_external && "no external sources",
    rule.disallow_http && "no http: sources",
    rule.disallow_data && "no data: sources",
    rule.disallow_blob && "no blob: sources",
  ]
    .filter(Boolean)
    .join(", ");
}

function policySection(
  doc: jsPDF,
  y: number,
  view: PolicyView,
  note: string | null | undefined
): number {
  y = beginSection(doc, y, "Policy Applied", "These are the rules against which this scan was evaluated.", { minSpace: 200 });

  // Identity card
  const descLines = view.description ? (doc.splitTextToSize(view.description, CONTENT_W - 28) as string[]).slice(0, 4) : [];
  const cardH = 44 + descLines.length * 11;
  y = ensureSpace(doc, y, cardH + 10);
  doc.setFillColor(...ACCENT_SOFT);
  doc.setDrawColor(255, 214, 184);
  doc.setLineWidth(0.6);
  doc.roundedRect(MARGIN_X, y, CONTENT_W, cardH, 6, 6, "FD");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(...INK);
  doc.text(view.name, MARGIN_X + 14, y + 21);
  if (view.version) {
    const nameW = doc.getTextWidth(view.name);
    doc.setFontSize(8);
    doc.setTextColor(...ACCENT);
    doc.text(view.version.toUpperCase(), MARGIN_X + 22 + nameW, y + 21);
  }
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(...MUTED);
  const counts =
    `${view.headers.length} header rule${view.headers.length === 1 ? "" : "s"}` +
    ` · Content-Security-Policy ${view.cspEvaluated ? "evaluated" : "not evaluated"}`;
  doc.text(counts, MARGIN_X + 14, y + 35);
  if (descLines.length) doc.text(descLines, MARGIN_X + 14, y + 48);
  y += cardH + 12;

  if (note) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    for (const line of doc.splitTextToSize(note, CONTENT_W) as string[]) {
      y = ensureSpace(doc, y, 12);
      doc.text(line, MARGIN_X, y);
      y += 11;
    }
    y += 4;
  }

  if (view.headers.length > 0) {
    autoTable(doc, {
      ...TABLE_STYLE,
      startY: y,
      head: [["Header", "Requirement", "Expected value"]],
      body: view.headers.map((h) => [
        h.header,
        h.required ? "Required" : "Optional",
        describeExpected(h.header, h.expected),
      ]),
      columnStyles: { 0: { cellWidth: 150, fontStyle: "bold" }, 1: { cellWidth: 70 } },
      didParseCell: (hook) => {
        if (hook.section === "body" && hook.column.index === 1) {
          hook.cell.styles.textColor = String(hook.cell.raw) === "Required" ? INK : MUTED;
        }
      },
    });
    y = finalY(doc) + 16;
  }

  // Content-Security-Policy rules
  if (view.csp) {
    y = ensureSpace(doc, y, 60);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...INK);
    doc.text("Content-Security-Policy rules", MARGIN_X, y);
    y += 6;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(...MUTED);
    y += 10;
    doc.text(`Header required: ${view.csp.required ? "Yes" : "No"}`, MARGIN_X, y);
    if (view.csp.required_directives.length > 0) {
      y += 12;
      const req = doc.splitTextToSize(`Required directives: ${view.csp.required_directives.join(", ")}`, CONTENT_W) as string[];
      for (const line of req) {
        y = ensureSpace(doc, y, 12);
        doc.text(line, MARGIN_X, y);
        y += 11;
      }
      y -= 11;
    }
    y += 10;
    if (view.csp.directive_rules.length > 0) {
      autoTable(doc, {
        ...TABLE_STYLE,
        startY: y,
        head: [["Directive", "Must contain", "Must not contain", "Allowed sources", "Restrictions"]],
        body: view.csp.directive_rules.map((r) => [
          r.directive,
          r.must_contain.join(", ") || "-",
          r.must_not_contain.join(", ") || "-",
          r.allowed_sources ? r.allowed_sources.join(", ") || "(none)" : "-",
          ruleRestrictions(r) || "-",
        ]),
        columnStyles: { 0: { fontStyle: "bold", cellWidth: 80 } },
      });
      y = finalY(doc) + 16;
    } else {
      y += 4;
    }
  } else if (view.cspChecks.length > 0) {
    y = ensureSpace(doc, y, 60);
    autoTable(doc, {
      ...TABLE_STYLE,
      startY: y,
      head: [["ID", "Content-Security-Policy rule", "Expected"]],
      body: view.cspChecks.map((c) => [c.id, c.description, c.expected]),
      columnStyles: { 0: { cellWidth: 60, fontStyle: "bold" } },
    });
    y = finalY(doc) + 16;
  }
  return y;
}

// ---- document -----------------------------------------------------------------

// ---- expected-value wording ----------------------------------------------------

/** Plain-language form of a policy's expected value. Cache-Control's mini-syntax
 * (`a, b` = exact set, trailing `+` = extras allowed, `!x` = prohibited) is
 * spelled out so a reader never has to guess whether extra directives fail. */
function describeExpected(header: string, value: string | null | undefined): string {
  const text = (value ?? "").trim();
  if (!text) return "Present (any value)";
  if (header.trim().toLowerCase() !== "cache-control") return text;
  const tokens = text.split(",").map((t) => t.trim()).filter(Boolean);
  const extrasAllowed = tokens.includes("+");
  const prohibited = tokens.filter((t) => t.startsWith("!")).map((t) => t.slice(1));
  const required = tokens.filter((t) => t !== "+" && !t.startsWith("!"));
  const parts = [];
  if (required.length) parts.push(`Required: ${required.join(", ")}`);
  if (prohibited.length) parts.push(`Prohibited: ${prohibited.join(", ")}`);
  parts.push(extrasAllowed ? "Extra directives: allowed" : "Extra directives: not allowed (exact set)");
  return parts.join("\n");
}

// ---- findings model --------------------------------------------------------------

const SEVERITY_ORDER: SeverityLevel[] = ["critical", "high", "medium", "low", "info"];
const SEVERITY_COLOR: Record<SeverityLevel, RGB> = {
  critical: [150, 20, 20],
  high: [200, 50, 50],
  medium: [200, 130, 20],
  low: [70, 120, 180],
  info: [120, 120, 128],
};
const POLICY_TAG: RGB = ACCENT;
const BEST_PRACTICE_TAG: RGB = [90, 100, 200];

type IssueSource = "header" | "csp-policy" | "csp-best-practice";

/** Something the reader may need to act on: a failed check or a warning.
 * PASS results and INFO notes are never findings. */
interface Issue {
  label: string;
  message: string;
  severity: SeverityLevel;
  status: "FAIL" | "WARNING";
  source: IssueSource;
}

function cspIssues(csp: CSPFinding | null): Issue[] {
  if (!csp) return [];
  const toIssue = (c: CheckResult, source: IssueSource): Issue | null =>
    c.status === "FAIL" || c.status === "WARNING"
      ? { label: c.id ?? "CSP", message: c.description, severity: c.severity ?? "info", status: c.status, source }
      : null;
  return [
    ...csp.policy_checks.map((c) => toIssue(c, "csp-policy")),
    ...csp.security_checks.map((c) => toIssue(c, "csp-best-practice")),
  ].filter((i): i is Issue => i !== null);
}

function headerIssues(findings: HeaderFinding[]): Issue[] {
  const issues: Issue[] = [];
  for (const f of findings) {
    if (f.status === "FAIL") {
      issues.push({
        label: f.header,
        message: f.issue ?? "The value does not comply with the configured policy.",
        severity: f.severity,
        status: "FAIL",
        source: "header",
      });
    }
    for (const a of f.advisories ?? []) {
      if (a.status === "WARNING") {
        issues.push({ label: f.header, message: `${a.title}. ${a.message}`, severity: a.severity, status: "WARNING", source: "header" });
      }
    }
  }
  return issues;
}

function rankIssues(issues: Issue[]): Issue[] {
  return [...issues].sort(
    (a, b) =>
      SEVERITY_ORDER.indexOf(a.severity) - SEVERITY_ORDER.indexOf(b.severity) ||
      (a.status === b.status ? 0 : a.status === "FAIL" ? -1 : 1)
  );
}

function assessment(grade: string): string {
  switch (grade) {
    case "A":
      return "Excellent - the header configuration meets the policy.";
    case "B":
      return "Good - most checks pass, with a few gaps to close.";
    case "C":
      return "Fair - several checks failed against the policy.";
    case "D":
      return "Weak - many checks failed against the policy.";
    default:
      return "Needs attention - most checks failed against the policy.";
  }
}

function plural(n: number, one: string, many: string): string {
  return n === 1 ? one : many;
}

function smallHeading(doc: jsPDF, x: number, y: number, text: string): void {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8.5);
  doc.setTextColor(...MUTED);
  doc.text(text.toUpperCase(), x, y);
}

function severityTag(doc: jsPDF, x: number, y: number, text: string, color: RGB): number {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  const w = doc.getTextWidth(text) + 10;
  doc.setFillColor(...color);
  doc.roundedRect(x, y, w, 13, 3, 3, "F");
  doc.setTextColor(255, 255, 255);
  doc.text(text, x + 5, y + 9.3);
  return w;
}

// ---- page 1: executive summary, severity, key findings ---------------------------------

function executiveSummary(doc: jsPDF, y: number, data: PdfReportData): number {
  const headersPassed = data.findings.filter((f) => f.status === "PASS").length;
  const headersFailed = data.findings.filter((f) => f.status === "FAIL").length;
  const total = data.findings.length;
  const csp = data.csp_finding;
  const gap = 10;
  const tileW = (CONTENT_W - gap * 2) / 3;
  const at = (i: number) => MARGIN_X + i * (tileW + gap);

  y = sectionHeading(doc, y, "Executive Summary");
  statTile(doc, at(0), y, tileW, `Header ${plural(headersPassed, "rule", "rules")} passed`, total ? `${headersPassed} / ${total}` : "n/a", total ? PASS : MUTED);
  statTile(doc, at(1), y, tileW, `Header ${plural(headersFailed, "rule", "rules")} failed`, total ? `${headersFailed} / ${total}` : "n/a", headersFailed > 0 ? FAIL : MUTED);
  statTile(doc, at(2), y, tileW, `Header ${plural(total, "rule", "rules")} checked`, String(total), INK);
  y += 46 + gap;
  if (csp) {
    const pctColor = (done: number, of: number): RGB => (of === 0 ? MUTED : done === of ? PASS : done / of >= 0.6 ? WARN : FAIL);
    statTile(doc, at(0), y, tileW, "CSP policy checks passed", `${csp.policy_checks_passed} / ${csp.policy_checks_total}`, pctColor(csp.policy_checks_passed, csp.policy_checks_total));
    statTile(doc, at(1), y, tileW, "CSP best-practice checks passed", `${csp.best_practice_passed} / ${csp.best_practice_total}`, pctColor(csp.best_practice_passed, csp.best_practice_total));
    statTile(doc, at(2), y, tileW, "Overall CSP score", String(csp.overall_score), INK);
    y += 46 + gap;
  } else {
    // Same three tiles, so the layout doesn't change when CSP isn't evaluated.
    statTile(doc, at(0), y, tileW, "CSP policy checks passed", "N/A", MUTED);
    statTile(doc, at(1), y, tileW, "CSP best-practice checks passed", "N/A", MUTED);
    statTile(doc, at(2), y, tileW, "Overall CSP score", "N/A", MUTED);
    y += 46 + gap;
  }
  return y;
}

/** Small section heading used inside page 1 (lighter than a full section). */
function sectionHeading(doc: jsPDF, y: number, title: string): number {
  doc.setFillColor(...ACCENT);
  doc.roundedRect(MARGIN_X, y - 11, 3.5, 15, 1.5, 1.5, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...INK);
  doc.text(title, MARGIN_X + 11, y);
  return y + 16;
}

function severityBreakdown(doc: jsPDF, y: number, issues: Issue[]): number {
  y = sectionHeading(doc, y, "Findings by Severity");
  const counts = SEVERITY_ORDER.map((sev) => issues.filter((i) => i.severity === sev).length);
  const max = Math.max(1, ...counts);
  const labelW = 60;
  const barX = MARGIN_X + labelW;
  const barW = CONTENT_W - labelW - 40;
  SEVERITY_ORDER.forEach((sev, i) => {
    const ry = y + i * 18;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(...INK);
    doc.text(sev[0].toUpperCase() + sev.slice(1), MARGIN_X, ry + 8);
    doc.setFillColor(...LINE);
    doc.roundedRect(barX, ry, barW, 10, 5, 5, "F");
    if (counts[i] > 0) {
      doc.setFillColor(...SEVERITY_COLOR[sev]);
      doc.roundedRect(barX, ry, Math.max(10, (barW * counts[i]) / max), 10, 5, 5, "F");
    }
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...(counts[i] > 0 ? INK : MUTED));
    doc.text(String(counts[i]), PAGE_W - MARGIN_X, ry + 8, { align: "right" });
  });
  y += SEVERITY_ORDER.length * 18;
  return y + 20;
}

const KEY_FINDINGS_SHOWN = 5;

function keyFindings(doc: jsPDF, y: number, issues: Issue[], cspEvaluated: boolean): number {
  y = sectionHeading(doc, y, "Key Findings");
  if (issues.length === 0) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...PASS);
    doc.text("No issues found.", MARGIN_X, y + 6);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(...MUTED);
    doc.text(cspEvaluated ? "Every header rule and CSP check passed." : "Every header rule passed.", MARGIN_X, y + 19);
    return y + 34;
  }
  const ranked = rankIssues(issues);
  const shown = ranked.slice(0, KEY_FINDINGS_SHOWN);
  for (const item of shown) {
    y = ensureSpace(doc, y, 34);
    const tagW = severityTag(doc, MARGIN_X, y, item.severity.toUpperCase(), SEVERITY_COLOR[item.severity]);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(...INK);
    const textX = MARGIN_X + tagW + 8;
    const lines = (doc.splitTextToSize(`${item.label} - ${item.message}`, CONTENT_W - tagW - 8) as string[]).slice(0, 2);
    doc.setFont("helvetica", "normal");
    doc.text(lines, textX, y + 10);
    y += Math.max(20, lines.length * 11 + 9);
  }
  if (ranked.length > shown.length) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text(`+ ${ranked.length - shown.length} more ${plural(ranked.length - shown.length, "finding", "findings")} detailed later in this report`, MARGIN_X, y + 6);
    y += 16;
  }
  return y + 6;
}

// ---- recommendations ------------------------------------------------------------------

interface RecField {
  label: string;
  lines: string[];
}

function recommendationCard(doc: jsPDF, y: number, title: string, tagText: string, tagColor: RGB, fields: RecField[]): number {
  const labelW = 70;
  const lineH = 10.5;
  const bodyH = fields.reduce((sum, f) => sum + f.lines.length * lineH + 4, 0);
  const h = 30 + bodyH;
  y = ensureSpace(doc, y, h + 8);
  doc.setFillColor(...CARD);
  doc.setDrawColor(...LINE);
  doc.setLineWidth(0.5);
  doc.roundedRect(MARGIN_X, y, CONTENT_W, h, 5, 5, "FD");
  doc.setFillColor(...tagColor);
  doc.roundedRect(MARGIN_X, y, 3.5, h, 1.5, 1.5, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...INK);
  doc.text(title, MARGIN_X + 14, y + 17);
  severityTag(doc, MARGIN_X + 14 + doc.getTextWidth(title) + 8, y + 7, tagText, tagColor);
  let fy = y + 32;
  for (const field of fields) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7.5);
    doc.setTextColor(...MUTED);
    doc.text(field.label.toUpperCase(), MARGIN_X + 14, fy);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(...INK);
    doc.text(field.lines, MARGIN_X + 14 + labelW, fy);
    fy += field.lines.length * lineH + 4;
  }
  return y + h + 8;
}

function wrap(doc: jsPDF, text: string, width: number): string[] {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  return doc.splitTextToSize(text, width) as string[];
}

function recommendations(doc: jsPDF, y: number, data: PdfReportData): number {
  const textW = CONTENT_W - 28 - 70;
  const failing = data.findings.filter((f) => f.status !== "PASS" && (f.issue || f.recommendation));
  const notes = data.findings.flatMap((f) => (f.advisories ?? []).map((a) => ({ header: f.header, advisory: a })));
  if (failing.length === 0 && notes.length === 0) return y;

  y = beginSection(doc, y, "Recommendations", "What to change, and why. Expected and actual values are shown side by side.", { minSpace: 170 });
  for (const f of failing) {
    y = recommendationCard(doc, y, f.header, f.severity.toUpperCase(), SEVERITY_COLOR[f.severity], [
      { label: "Issue", lines: wrap(doc, f.issue ?? "The value does not comply with the configured policy.", textW) },
      { label: "Expected", lines: wrap(doc, describeExpected(f.header, f.policy_expected).replace(/\n/g, "; "), textW) },
      { label: "Actual", lines: wrap(doc, f.actual_value ?? "(header not present)", textW) },
      { label: "Remediation", lines: wrap(doc, f.recommendation ?? "Update the header so its value complies with the configured policy.", textW) },
    ]);
  }
  for (const { header, advisory } of notes) {
    y = recommendationCard(doc, y, header, advisory.status, STATUS_COLOR[advisory.status] ?? MUTED, [
      { label: "Note", lines: wrap(doc, `${advisory.title}. ${advisory.message}`, textW) },
      ...(advisory.recommendation ? [{ label: "Action", lines: wrap(doc, advisory.recommendation, textW) }] : []),
    ]);
  }
  return y;
}

// ---- Content-Security-Policy ------------------------------------------------------------

const RISKY_SOURCES = ["'unsafe-inline'", "'unsafe-eval'", "*", "http:"];
const CAUTION_SOURCES = ["data:", "blob:"];

function cspReceived(doc: jsPDF, y: number, csp: CSPFinding): number {
  smallHeading(doc, MARGIN_X, y, "CSP received");
  y += 10;
  if (!csp.present || !csp.actual_value) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(...MUTED);
    doc.text("The response did not include a Content-Security-Policy header.", MARGIN_X, y + 8);
    return y + 26;
  }
  // One row per directive: its name, then its sources.
  const rows = csp.actual_value
    .split(";")
    .map((d) => d.trim())
    .filter(Boolean)
    .map((d) => {
      const [name, ...sources] = d.split(/\s+/);
      return [name, sources.length ? sources.join("   ") : "(no sources)"];
    });
  y = ensureSpace(doc, y, 60);
  autoTable(doc, {
    ...TABLE_STYLE,
    startY: y,
    head: [["Directive", "Sources"]],
    body: rows,
    styles: { ...TABLE_STYLE.styles, font: "courier", fontSize: 8, cellPadding: 5 },
    headStyles: { ...TABLE_STYLE.headStyles, font: "helvetica" },
    columnStyles: { 0: { cellWidth: 110, fontStyle: "bold", textColor: ACCENT } },
    didParseCell: (hook) => {
      if (hook.section !== "body" || hook.column.index !== 1) return;
      const tokens = String(hook.cell.raw).split(/\s+/).filter(Boolean);
      if (String(hook.cell.raw) === "(no sources)") hook.cell.styles.textColor = MUTED;
      else if (tokens.some((t) => RISKY_SOURCES.includes(t))) hook.cell.styles.textColor = FAIL;
      else if (tokens.some((t) => CAUTION_SOURCES.includes(t))) hook.cell.styles.textColor = WARN;
    },
  });
  y = finalY(doc) + 6;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(...MUTED);
  doc.text("Red: contains a risky source ('unsafe-inline', 'unsafe-eval', *, http:).  Amber: contains data: or blob:.", MARGIN_X, y + 6);
  return y + 30;
}

function cspFindings(doc: jsPDF, y: number, csp: CSPFinding): number {
  const issues = rankIssues(cspIssues(csp));
  const policyCount = issues.filter((i) => i.source === "csp-policy").length;
  const bpCount = issues.filter((i) => i.source === "csp-best-practice").length;
  y = ensureSpace(doc, y, 60);
  smallHeading(doc, MARGIN_X, y, "CSP findings");
  y += 12;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(...INK);
  doc.text(`${policyCount} policy ${plural(policyCount, "issue", "issues")}   ·   ${bpCount} best-practice ${plural(bpCount, "issue", "issues")}`, MARGIN_X, y + 6);
  y += 20;
  if (issues.length === 0) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(...PASS);
    doc.text("No CSP issues found.", MARGIN_X, y + 6);
    return y + 22;
  }
  const textW = CONTENT_W - 130;
  for (const item of issues) {
    const lines = wrap(doc, `${item.label}  ${item.message}`, textW);
    y = ensureSpace(doc, y, lines.length * 11 + 12);
    severityTag(doc, MARGIN_X, y, item.severity.toUpperCase(), SEVERITY_COLOR[item.severity]);
    severityTag(doc, MARGIN_X + 58, y, item.source === "csp-policy" ? "POLICY" : "BEST PRACTICE", item.source === "csp-policy" ? POLICY_TAG : BEST_PRACTICE_TAG);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(...INK);
    doc.text(lines, MARGIN_X + 140, y + 10);
    y += Math.max(20, lines.length * 11 + 8);
  }
  return y + 8;
}

/** Checks grouped by directive, with a group row per directive, so the many
 * repeated per-directive checks (wildcard, external, http, data, blob...) read
 * as one block each instead of one long undifferentiated table. */
function cspDetailRows(csp: CSPFinding): unknown[][] {
  const all: { check: CheckResult; category: string }[] = [
    ...csp.policy_checks.map((check) => ({ check, category: "Policy" })),
    ...csp.security_checks.map((check) => ({ check, category: "Best practice" })),
  ];
  const groups = new Map<string, typeof all>();
  for (const item of all) {
    const key = item.check.directive ?? "General";
    groups.set(key, [...(groups.get(key) ?? []), item]);
  }
  const rows: unknown[][] = [];
  for (const [directive, items] of groups) {
    rows.push([{ content: directive, colSpan: 7, styles: { fillColor: ACCENT_SOFT, fontStyle: "bold", textColor: INK } }]);
    for (const { check, category } of items) {
      rows.push([
        check.id ?? "-",
        category,
        check.description,
        check.severity ?? "-",
        check.status,
        check.expected ?? "-",
        check.actual ?? "-",
      ]);
    }
  }
  return rows;
}

function cspSection(doc: jsPDF, y: number, csp: CSPFinding): number {
  y = beginSection(doc, y, "Content-Security-Policy Analysis", "Where the CSP stands first; the detailed evidence follows.", { minSpace: 260 });
  const gap = 10;
  const tileW = (CONTENT_W - gap * 2) / 3;
  const at = (i: number) => MARGIN_X + i * (tileW + gap);
  const tone = (done: number, of: number): RGB => (of === 0 ? MUTED : done === of ? PASS : done / of >= 0.6 ? WARN : FAIL);
  statTile(doc, at(0), y, tileW, "Overall CSP score", `${csp.overall_score} / 100`, INK);
  statTile(doc, at(1), y, tileW, "Policy compliance", `${csp.policy_checks_passed} / ${csp.policy_checks_total}`, tone(csp.policy_checks_passed, csp.policy_checks_total));
  statTile(doc, at(2), y, tileW, "Best practice", `${csp.best_practice_passed} / ${csp.best_practice_total}`, tone(csp.best_practice_passed, csp.best_practice_total));
  y += 46 + 20;
  y = cspReceived(doc, y, csp);
  y = cspFindings(doc, y, csp);

  y = beginSection(
    doc,
    y,
    "Detailed CSP Analysis",
    "Policy checks are the rules you configured. Best-practice checks are extra recommendations from Hedr - a policy check can pass while a best-practice check fails.",
    { newPage: true }
  );
  autoTable(doc, {
    ...TABLE_STYLE,
    startY: y,
    head: [["ID", "Category", "Check", "Severity", "Status", "Expected", "Actual"]],
    body: cspDetailRows(csp) as never,
    columnStyles: { 0: { fontStyle: "bold", cellWidth: 46 }, 1: { cellWidth: 66 } },
    didParseCell: (hook) => {
      if (hook.section !== "body") return;
      const raw = String(hook.cell.raw);
      if (hook.column.index === 4 && STATUS_COLOR[raw]) {
        hook.cell.styles.textColor = STATUS_COLOR[raw];
        hook.cell.styles.fontStyle = "bold";
      }
      if (hook.column.index === 1) {
        hook.cell.styles.textColor = raw === "Policy" ? POLICY_TAG : BEST_PRACTICE_TAG;
        hook.cell.styles.fontStyle = "bold";
      }
    },
  });
  return finalY(doc) + 16;
}

// ---- document ------------------------------------------------------------------------------

export function downloadReportPdf(data: PdfReportData, options: PdfOptions = {}): void {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  let y = CONTENT_TOP;

  // Page 1: what happened, is anything wrong, what policy was used.
  y = summaryCard(doc, y, data);
  y += 8;
  const issues = [...headerIssues(data.findings), ...cspIssues(data.csp_finding)];
  y = executiveSummary(doc, y + 12, data);
  y = severityBreakdown(doc, y + 18, issues);
  y = keyFindings(doc, y + 8, issues, Boolean(data.csp_finding));
  y = policySection(doc, y, buildPolicyView(data, options.policy), options.policyNote);

  // Evidence: each header against its expected value.
  if (data.findings.length > 0) {
    y = beginSection(
      doc,
      y,
      "Header Findings",
      "Status shows whether the response complies with the configured policy - not whether the header is modern best practice.",
      { minSpace: 200 }
    );
    autoTable(doc, {
      ...TABLE_STYLE,
      startY: y,
      head: [["Header", "Status", "Severity", "Score", "Policy Expected", "Actual Value"]],
      body: data.findings.map((f) => {
        // Keep the raw value; show what it normalized to when that is why it matched.
        const normalized = f.checks.map((c) => c.evidence).find((e) => e);
        return [
          f.header,
          f.status,
          f.severity,
          `${f.score_earned}/${f.score_possible}`,
          describeExpected(f.header, f.policy_expected),
          `${f.actual_value ?? "(missing)"}${normalized ? `\n(${normalized})` : ""}`,
        ];
      }),
      columnStyles: { 0: { fontStyle: "bold" }, 4: { cellWidth: 115 }, 5: { cellWidth: 115 } },
      didParseCell: statusColorHook(1),
    });
    y = finalY(doc) + 22;
  }

  y = recommendations(doc, y, data);

  if (data.csp_finding && data.csp_finding.policy_checks.length + data.csp_finding.security_checks.length > 0) {
    y = cspSection(doc, y, data.csp_finding);
  }

  decoratePages(doc, data);

  const slug = (data.target ?? "scan").replace(/[^a-z0-9]+/gi, "-").toLowerCase().slice(0, 40);
  const suffix = data.scan_number ? `scan-${data.scan_number}` : "result";
  doc.save(`hedr-${slug}-${suffix}.pdf`);
}
